### ISSUE TITLE
Start and stop stream too quickly causes crash

### ISSUE THREAD

**Issue by antonyharfield** [rfcx/rfcx-client-stream-android#40]

**Comment by antonyharfield** [comment]
`FATAL EXCEPTION: main
                                                                         Process: org.rfcx.android.stream, PID: 13998
                                                                         java.lang.IndexOutOfBoundsException: Invalid index 2, size is 2
                                                                             at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)
                                                                             at java.util.ArrayList.get(ArrayList.java:308)
                                                                             at org.rfcx.android.stream.streaming.StreamPlayback.nextStreamPlayback(StreamPlayback.java:396)
                                                                             at org.rfcx.android.stream.streaming.StreamPlayback.onResponse(StreamPlayback.java:499)
                                                                             at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall$1$1.run(ExecutorCallAdapterFactory.java:68)
                                                                             at android.os.Handler.handleCallback(Handler.java:739)`
